### PR TITLE
Add .js extensions to ESM imports

### PR DESCRIPTION
**Pull request by amacneil**
ESM in node.js currently requires explicit file extensions: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions

This results in the following webpack error when you try to consume this package as a module:

```
BREAKING CHANGE: The request './XmlRpcTypes' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Typescript, for better or worse have solved this by allowing TS files to import `*.js` and silently treating this as `.ts` instead. Massive thread if you want to get into it: https://github.com/microsoft/TypeScript/issues/16577#issuecomment-703190339

Jest of course doesn't understand any of this, and gets confused by the missing `.js` files. `ts-jest` doesn't solve this automatically, and neither does `esbuild-jest`. The best solution is a small custom jest resolver which attempts `.ts` as a fallback for `.js` imports. See this [ts-jest thread](https://github.com/kulshekhar/ts-jest/issues/1057) for details. Someone published this as a package ([jest-ts-webcompat-resolver](https://www.npmjs.com/package/jest-ts-webcompat-resolver)).

### CODE REVIEW

**Comment by jtbandes** [comment]
Is there any solution that allows us to keep "sane" (intuitive) import statements in our code?

**Comment by amacneil** [comment]
Explicit file extensions appear to be part of the ESM spec, so not really. It seems to me like typescript should rewrite them (from .ts to .js), but they have taken a stance against doing that.

So, our options are:
1. Don't use ESM
2. Run node with `--experimental-specifier-resolution=node` (I assume webpack, jest, etc would need equivalent configurations): https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm

**Comment by amacneil** [comment]
I'm going to merge, but feel free to continue researching and let me know if I'm missing anything obvious.

Another alternative I didn't mention is to use rollup or similar, and ship a single bundle file rather than a folder full of files. That way consumers don't need to worry about what our import statements look like.

**Comment by jtbandes** [comment]
Why do we care about ESM?

**Comment by amacneil** [comment]
If we ship commonjs then I don't think the package can be easily used in a browser? Also seems like ecosystem is moving that way? Some packages ship both commonjs + esm.

**Pull request merged**
